/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saini
 */
public class placeorder extends javax.swing.JFrame {

    /**
     * Creates new form placeorder
     */
    String uemail = "", uname = "";

    public placeorder(String a) {
        initComponents();
        uemail = a;

        try {

            addtocart.setEnabled(false);
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/shub", "root", "");

            java.sql.PreparedStatement p = con.prepareStatement("select * from category");
            ResultSet r = p.executeQuery();
            while (r.next()) {
                categoryy.addItem(r.getString("name"));
            }

            java.sql.PreparedStatement pa = con.prepareStatement("select * from cafe where email=? ");
            pa.setString(1, a);
            ResultSet ra = pa.executeQuery();
            if (ra.next()) {
                usname.setText(ra.getString("name"));
            }

            String q = categoryy.getSelectedItem() + "";
            java.sql.PreparedStatement z = con.prepareStatement("select * from product where category = ?");
            z.setString(1, q);
            ResultSet x = z.executeQuery();

            DefaultTableModel tbmodel = (DefaultTableModel) table1.getModel();
            tbmodel.setRowCount(0);

            while (x.next()) {
                String zx = x.getString("name");
                String data[] = {zx};
                tbmodel.addRow(data);
            }


        } catch (SQLException ex) {
            Logger.getLogger(placeorder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private placeorder() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnameT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        categoryy = new javax.swing.JComboBox();
        pprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        psearch = new javax.swing.JTextField();
        ptotal = new javax.swing.JTextField();
        pquantity = new javax.swing.JSpinner();
        addtocart = new javax.swing.JButton();
        OrderB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        usname = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setText("Place Order");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Category ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 121, -1, -1));

        pnameT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pnameT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameTActionPerformed(evt);
            }
        });
        jPanel1.add(pnameT, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 149, 255, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 121, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 121, 57, -1));

        categoryy.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        categoryy.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                categoryyPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(categoryy, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 149, 268, -1));

        pprice.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppriceActionPerformed(evt);
            }
        });
        jPanel1.add(pprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 149, 255, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Search");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 183, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Total");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 183, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Quantity");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 183, -1, -1));

        psearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        psearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psearchActionPerformed(evt);
            }
        });
        jPanel1.add(psearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 214, 268, -1));

        ptotal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ptotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptotalActionPerformed(evt);
            }
        });
        jPanel1.add(ptotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 214, 255, -1));

        pquantity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pquantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pquantityStateChanged(evt);
            }
        });
        jPanel1.add(pquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 214, 255, -1));

        addtocart.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addtocart.setText("Add to Cart");
        addtocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartActionPerformed(evt);
            }
        });
        jPanel1.add(addtocart, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 270, -1, -1));

        OrderB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        OrderB.setText("Order");
        OrderB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderBActionPerformed(evt);
            }
        });
        jPanel1.add(OrderB, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 571, -1, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 270, 268, 290));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        jScrollPane2.setViewportView(table2);
        table2.getColumnModel().getColumn(1).setHeaderValue("Price");
        table2.getColumnModel().getColumn(2).setHeaderValue("Quantity");
        table2.getColumnModel().getColumn(3).setHeaderValue("Total");

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 312, 566, 238));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("User");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 70, 48, -1));

        usname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        usname.setText(" ");
        jPanel1.add(usname, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 70, 100, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 270, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void OrderBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderBActionPerformed
        System.out.println("Under Construction.");
    }//GEN-LAST:event_OrderBActionPerformed

    private void addtocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartActionPerformed

        DefaultTableModel tbmodel = (DefaultTableModel) table2.getModel();
        String name = pnameT.getText();
        String price = pprice.getText();
        String quantity = pquantity.getValue() + "";
        String total = ptotal.getText();
        String data[] = {name, price, quantity, total};
        tbmodel.addRow(data);
        pnameT.setText("");
        pprice.setText("");
        pquantity.setValue(0);
        ptotal.setText("");
        addtocart.setEnabled(false);
    }//GEN-LAST:event_addtocartActionPerformed

    private void ptotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptotalActionPerformed

    private void psearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psearchActionPerformed

    private void ppriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppriceActionPerformed

    private void categoryyPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_categoryyPopupMenuWillBecomeInvisible
        String nname = categoryy.getSelectedItem() + "";

        try {
            // TODO add your handling code here:
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/shub", "root", "");
            java.sql.PreparedStatement p = con.prepareStatement("select * from product where category=?");
            p.setString(1, nname);

            ResultSet r = p.executeQuery();
            DefaultTableModel tbmodel = (DefaultTableModel) table1.getModel();
            tbmodel.setRowCount(0);
            while (r.next()) {
                String name = r.getString("name");
                String data[] = {name};
                tbmodel.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(placeorder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_categoryyPopupMenuWillBecomeInvisible

    private void pnameTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameTActionPerformed

    String b = "";
    
    private void table1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MousePressed
        ptotal.setText("0");
        DefaultTableModel tbmodel = (DefaultTableModel) table1.getModel();
        String Pname = String.valueOf(tbmodel.getValueAt(table1.getSelectedRow(), table1.getSelectedColumn()));
        
        try {
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/shub", "root", "");
            java.sql.PreparedStatement p = con.prepareStatement("select * from product where name = ?");
            p.setString(1, Pname);
            ResultSet r = p.executeQuery();
            
            if(r.next())
            {
                pnameT.setText(Pname);
                pprice.setText(r.getString("price"));
                b = r.getString("price");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(placeorder.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_table1MousePressed

    private void pquantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pquantityStateChanged
        // TODO add your handling code here:
        int apprice = Integer.parseInt(b);
        String a = String.valueOf(pquantity.getValue());
        int pquan = Integer.parseInt(a);
        int c = pquan * apprice;
        String aptotal = String.valueOf(c);
        
        ptotal.setText(aptotal);
        
        addtocart.setEnabled(true);
    }//GEN-LAST:event_pquantityStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             cafehome ob= new cafehome(uemail);
             ob.setVisible(true);
             setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    String Oname = "";

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(placeorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(placeorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(placeorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(placeorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new placeorder().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OrderB;
    private javax.swing.JButton addtocart;
    private javax.swing.JComboBox categoryy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pnameT;
    private javax.swing.JTextField pprice;
    private javax.swing.JSpinner pquantity;
    private javax.swing.JTextField psearch;
    private javax.swing.JTextField ptotal;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JLabel usname;
    // End of variables declaration//GEN-END:variables
}
